products = [
    {
        "_id": 1,
        "description": "Raw organic brown eggs in a basket",
        "price": 28.1,
        "rating": 4,
        "title": "Brown eggs",
        "type": "dairy",
    },
    {
        "_id": 2,
        "description": "Sweet fresh strawberry on the wooden table",
        "price": 29.45,
        "rating": 4,
        "title": "Sweet fresh strawberry",
        "type": "fruit",
    },
    {
        "_id": 3,
        "description": "Asparagus with ham on the wooden table",
        "price": 18.95,
        "rating": 3,
        "title": "Asparagus",
        "type": "vegetable",
    },
    {
        "_id": 4,
        "description": "Glass of green smoothie with quail egg's yolk",
        "price": 17.68,
        "rating": 4,
        "title": "Green smoothie",
        "type": "dairy",
    },
    {
        "_id": 5,
        "description": "Raw legums on the wooden table",
        "price": 17.11,
        "rating": 2,
        "title": "Raw legums",
        "type": "vegetable",
    },
    {
        "_id": 6,
        "description": "Baking cake in rural kitchen - dough recipe",
        "price": 11.14,
        "rating": 4,
        "title": "Baking cake",
        "type": "dairy",
    },
    {
        "_id": 7,
        "description": "Italian traditional pesto with basil, cheese and oil",
        "price": 18.19,
        "rating": 2,
        "title": "Pesto with basil",
        "type": "vegetable",
    },
    {
        "_id": 8,
        "description": "Hazelnut in black ceramic bowl on old wooden background",
        "price": 27.35,
        "rating": 0,
        "title": "Hazelnut in black ceramic bowl",
        "type": "vegetable",
    },
    {
        "_id": 9,
        "description": "Fresh strawberry on the wooden table",
        "price": 28.59,
        "rating": 4,
        "title": "Fresh strawberry",
        "type": "fruit",
    },
    {
        "_id": 10,
        "description": "Rosemary, lemon and salt on the table",
        "price": 15.79,
        "rating": 5,
        "title": "Lemon and salt",
        "type": "fruit",
    },
    {
        "_id": 11,
        "description": "Homemade bread",
        "price": 17.48,
        "rating": 3,
        "title": "Homemade bread",
        "type": "bakery",
    },
    {
        "_id": 12,
        "description": "Cooked legums on the wooden table",
        "price": 14.77,
        "rating": 0,
        "title": "Legums",
        "type": "vegetable",
    },
    {
        "_id": 13,
        "description": "Fresh tomato juice with basil",
        "price": 16.3,
        "rating": 2,
        "title": "Fresh tomato",
        "type": "vegetable",
    },
    {
        "_id": 14,
        "description": "Healthy breakfast set with berries and honey",
        "price": 13.02,
        "rating": 2,
        "title": "Healthy breakfast",
        "type": "fruit",
    },
    {
        "_id": 15,
        "description": "Raw organic green beans ready to eat",
        "price": 28.79,
        "rating": 1,
        "title": "Green beans",
        "type": "vegetable",
    },
    {
        "_id": 16,
        "description": "Homemade baked stuffed mushrooms with spinach and cheese",
        "price": 20.31,
        "rating": 1,
        "title": "Stuffed mushrooms",
        "type": "bakery",
    },
    {
        "_id": 17,
        "description": "Homemade organic strawberry jelly in a jar",
        "price": 14.18,
        "rating": 1,
        "title": "Strawberry jelly",
        "type": "fruit",
    },
    {
        "_id": 18,
        "description": "Fresh pears juice on the wooden table",
        "price": 19.49,
        "rating": 4,
        "title": "Pears juice",
        "type": "fruit",
    },
    {
        "_id": 19,
        "description": "Sweet fresh pears on the wooden table",
        "price": 15.12,
        "rating": 5,
        "title": "Fresh pears",
        "type": "fruit",
    },
    {
        "_id": 20,
        "description": "Homemade healthy caprese salad with tomato mozzarella and basil",
        "price": 16.76,
        "rating": 5,
        "title": "Caprese salad",
        "type": "vegetable",
    },
    {
        "_id": 21,
        "description": "Orange popsicle ice cream bars made from fresh oranges",
        "price": 21.48,
        "rating": 4,
        "title": "Oranges",
        "type": "fruit",
    },
    {
        "_id": 22,
        "description": "Concept of vegan food",
        "price": 29.66,
        "rating": 4,
        "title": "Vegan food",
        "type": "vegetable",
    },
    {
        "_id": 23,
        "description": "Healthy breakfast with muesli",
        "price": 22.7,
        "rating": 2,
        "title": "Breakfast with muesli",
        "type": "dairy",
    },
    {
        "_id": 24,
        "description": "Honey and honeycomb on the table",
        "price": 17.01,
        "rating": 2,
        "title": "Honey",
        "type": "bakery",
    },
    {
        "_id": 25,
        "description": "Healthy breakfast with cottage cheese and strawberry",
        "price": 14.05,
        "rating": 1,
        "title": "Breakfast with cottage",
        "type": "fruit",
    },
    {
        "_id": 26,
        "description": "Glass of red strawberry smoothie with chia seeds",
        "price": 28.86,
        "rating": 2,
        "title": "Strawberry smoothie",
        "type": "fruit",
    },
    {
        "_id": 27,
        "description": "Homemade muesli with strawberry and mint",
        "price": 26.21,
        "rating": 4,
        "title": "Strawberry and mint",
        "type": "fruit",
    },
    {
        "_id": 28,
        "description": "Ricotta with berry and mint",
        "price": 27.81,
        "rating": 5,
        "title": "Ricotta",
        "type": "dairy",
    },
    {
        "_id": 29,
        "description": "Traditional cuban sandwiches with ham pork and cheese",
        "price": 18.5,
        "rating": 4,
        "title": "Cuban sandwich",
        "type": "bakery",
    },
    {
        "_id": 30,
        "description": "Glass jar with homemade granola and yogurt",
        "price": 29.97,
        "rating": 3,
        "title": "Granola",
        "type": "dairy",
    },
    {
        "_id": 31,
        "description": "Smoothie with chia seeds",
        "price": 25.26,
        "rating": 5,
        "title": "Smoothie with chia seeds",
        "type": "fruit",
    },
    
     {
    "_id": 32,
    "description": "Mix of rum, lemon juice, mint, sugar and sparking water",
    "price": 27.61,
    "rating": 4,
    "title": "Mojito",
    "type": "drink",
},

    {
        "_id": 33,
        "description": "Vegan sandwich with salad, tomato and radish",
        "price": 22.48,
        "rating": 5,
        "title": "Sandwich with salad",
        "type": "vegetable",
    },
    {
        "_id": 34,
        "description": "Cherry with sugar on old table",
        "price": 14.35,
        "rating": 5,
        "title": "Cherry",
        "type": "fruit",
    },
    {
        "_id": 35,
        "description": "Raw fresh asparagus salad with cheese and dressing",
        "price": 22.97,
        "rating": 4,
        "title": "Raw asparagus",
        "type": "vegetable",
    },
    {
        "_id": 36,
        "description": "Grilled corn on the cob with salt and butter",
        "price": 13.55,
        "rating": 2,
        "title": "Corn",
        "type": "vegetable",
    },
    {
        "_id": 37,
        "description": "Homemade cola drink with lemon juice and 2 ice cubes",
        "price": 28.96,
        "rating": 5,
        "title": "Fresh Nuka-Cola",
        "type": "drink",
    },
    {
        "_id": 38,
        "description": "Healthy breakfast with berries and nuts",
        "price": 21.01,
        "rating": 4,
        "title": "Fresh blueberries",
        "type": "fruit",
    },
    {
        "_id": 39,
        "description": "Vegan sandwiches with smashed avocado, tomatoes and radish",
        "price": 25.88,
        "rating": 0,
        "title": "Smashed avocado",
        "type": "fruit",
    },
    {
        "_id": 40,
        "description": "Italian ciabatta bread cut in slices",
        "price": 15.18,
        "rating": 1,
        "title": "Italian ciabatta",
        "type": "bakery",
    },
    {
        "_id": 41,
        "description": "Rustic healthy breakfast set with buckwheat and milk",
        "price": 21.32,
        "rating": 0,
        "title": "Rustic breakfast",
        "type": "dairy",
    },
    {
        "_id": 42,
        "description": "Heap of whole and sliced lemons and limes with mint",
        "price": 27.14,
        "rating": 2,
        "title": "Sliced lemons",
        "type": "fruit",
    },
    {
        "_id": 43,
        "description": "Yellow and red sweet plums",
        "price": 19.18,
        "rating": 1,
        "title": "Plums",
        "type": "fruit",
    },
    {
        "_id": 44,
        "description": "Homemade oven baked french fries with ketchup",
        "price": 18.32,
        "rating": 3,
        "title": "French fries",
        "type": "bakery",
    },
    {
        "_id": 45,
        "description": "Rice cereal with fresh strawberry and honey",
        "price": 15.13,
        "rating": 3,
        "title": "Strawberries",
        "type": "fruit",
    },
    {
        "_id": 46,
        "description": "Raw ground beef burger with seasoning",
        "price": 11.73,
        "rating": 5,
        "title": "Ground beef burger",
        "type": "meat",
    },
    {
        "_id": 47,
        "description": "Organic tomatoes made with love",
        "price": 26.03,
        "rating": 4,
        "title": "Tomatoes",
        "type": "fruit",
    },
    {
        "_id": 48,
        "description": "Concept of vegan food with basil",
        "price": 15.19,
        "rating": 4,
        "title": "Basil",
        "type": "vegetable",
    },
    {
        "_id": 49,
        "description": "Abstract citrus fruits bouquet",
        "price": 18.18,
        "rating": 1,
        "title": "Fruits bouquet",
        "type": "fruit",
    },
    {
        "_id": 50,
        "description": "Peaches on branch with leaves and glasses with peach juice",
        "price": 25.62,
        "rating": 3,
        "title": "Peaches on branch",
        "type": "fruit",
    },
]
